stages:
  run_fraud_pipeline:
    cmd: python mlops_pipeline.py
    deps:
      - mlops_pipeline.py
      - creditcard.csv
      - params.yaml
    params:
      - pipeline.sample_size
      - pipeline.random_state
      - pipeline.test_size
    outs:
      - packaged_model/best_model.joblib
      - packaged_model/scaler.joblib
      - packaged_model/model_metadata.json
      - packaged_model/model_results.csv
