stages:
  run_full_mlops_cycle:
    cmd: python ../03_orchestration_prefect/03_prefect_mlops_pipeline.py
    deps:
      - ../01_data_versioning_dvc/01_creditcard_dataset.csv
      - ../02_feature_store_feast/feature_repo/02_fraud_feature_definitions.py
      - ../02_feature_store_feast/feature_repo/feature_store.yaml
      - ../03_orchestration_prefect/03_pipeline_params.yaml
      - ../03_orchestration_prefect/03_prefect_mlops_pipeline.py
    params:
      - ../03_orchestration_prefect/03_pipeline_params.yaml:
          - pipeline.sample_size
          - pipeline.random_state
          - pipeline.test_size
    outs:
      - ../02_feature_store_feast/feature_repo/data/02_fraud_feature_source.parquet
      - ../02_feature_store_feast/feature_repo/data/02_latest_online_features.json
      - ../06_model_artifacts_joblib/06_best_model.joblib
      - ../06_model_artifacts_joblib/06_scaler.joblib
      - ../06_model_artifacts_joblib/06_model_metadata.json
      - ../06_model_artifacts_joblib/06_model_results.csv

